### ISSUE TITLE
Python 3.5 support

### ISSUE THREAD

**Issue by nchammas** [spotify/luigi#1491]
Luigi may already work with Python 3.5, but since the README doesn't mention it I thought I'd ask.

Does Luigi support Python 3.5?

**Comment by erikbern** [comment]
Not sure – I haven't tried :)

If Travis supports Python 3.5, we can enable it and try!

**Comment by nchammas** [comment]
Looks like [Travis does support Python 3.5](https://docs.travis-ci.com/user/languages/python/#Choosing-Python-versions-to-test-against). Nice... they even have a nightly build of Python!

```yaml
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
```
